amia/amia/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest import views

router = routers.DefaultRouter()
router.register(r'appointments', views.AppointmentViewSet, basename='Appointment')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointment.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rest/', include(router.urls)),
    path('accounts/', include('django.contrib.auth.urls'))
]

amia/appointment/urls.py
from django.urls import path
from . import views


app_name = 'appointment'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_appointment/', views.add_appointment, name='add_appointment'),
    path('<appointment_id>/success/', views.success, name='success'),
]

amia/appointment/models.py
from django.db import models


class Appointment(models.Model):
    date_appointment = models.DateField(verbose_name="Дата записи")
    time_appointment = models.TimeField(verbose_name="Время записи")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия, имя, отчество", blank=True, null=True)
    date_of_birth = models.CharField(max_length=20, verbose_name="Дата рождения", blank=True, null=True)
    email = models.EmailField(verbose_name="E-mail", blank=True, null=True)
    date_of_write = models.DateTimeField(verbose_name="Дата записи", blank=True, null=True, auto_now=True)
    is_booked = models.BooleanField(verbose_name="Забронировано", default=False)
    comment = models.TextField(verbose_name="Комментарий к записи", blank=True, null=True)

    def __str__(self):
        return str(self.date_appointment) + ' ' + str(self.time_appointment) + ' ' + str(self.last_name)

    class Meta:
        ordering = ('pk',)
        verbose_name = 'Запись на тестирование'
        verbose_name_plural = 'Записи на тестирование'

amia/appointment/views.py
from django.shortcuts import render, get_object_or_404, redirect
import calendar
from datetime import datetime
from django.http import JsonResponse
from .models import Appointment
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize
from .months import MONTHS


def index(request):

    year = datetime.now().year
    month = datetime.now().month

    if 'month' in request.GET:
        month = int(request.GET.get('month', month))

    date_picker_html = get_date_picker_html(year, month)

    return render(request, 'appointment/index2.html',
                  {'dates': date_picker_html,
                   'month': month,
                   'month_prev': month-1,
                   'month_next': month+1,
                   'month_selected': MONTHS[month - 1],
                   })


def add_appointment(request):
    if request.method == 'GET':
        pass
    elif request.method == 'POST':
        appointment_id = request.POST['time_interval']
        year = datetime.now().year
        month = int(request.POST['month'])
        if validate(appointment_id):
            appointment = get_object_or_404(Appointment, pk=appointment_id)
            if appointment.is_booked:
                date_picker_html = get_date_picker_html(year, month)
                return render(request, 'appointment/index.html',
                              {'error_message': "Время уже занято",
                               'dates': date_picker_html,
                               'month': month,
                               'month_prev': month - 1,
                               'month_next': month + 1,
                               'month_selected': MONTHS[month - 1],
                               'last_name': request.POST['last_name'],
                               'comment': request.POST['comment'],
                               'date_of_birth': request.POST['date_of_birth']
                               })
            else:
                appointment.last_name = request.POST.get('last_name', '')
                appointment.date_of_birth = request.POST.get('date_of_birth', '')
                appointment.comment = request.POST.get('comment', '')
                appointment.is_booked = True
                appointment.save()
                return redirect('/' + str(appointment.id) + '/success/')
        else:
            date_picker_html = get_date_picker_html(year, month)
            return render(request, 'appointment/index.html', {'error_message': "Ошибка записи. Выберите дату и время!",
                                                              'dates': date_picker_html,
                                                              'month': month,
                                                              'month_prev': month - 1,
                                                              'month_next': month + 1,
                                                              'month_selected': MONTHS[month - 1],
                                                              'last_name': request.POST['last_name'],
                                                              'comment': request.POST['comment'],
                                                              'date_of_birth': request.POST['date_of_birth']
                                                              })


def validate(appointment_id):
    check = False
    if appointment_id != '':
        check = True
    return check


def success(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    return render(request, 'appointment/success.html', {
        'last_name': appointment.last_name,
        'date_appointment': appointment.date_appointment,
        'time': appointment.time_appointment, })


def get_date_picker_html(year, month):

    def get_date_html(day_data, month_day):
        css_classes = ['btn', 'date_picker_enabled', 'date_picker_item']
        append_br = ''
        disabled = ''
        if day_data.weekday() == 6 and day_data.month == month_day:
            css_classes.append('btn-outline-danger')
            append_br = '<br>'
        else:
            css_classes.append('btn-outline-primary')
        if day_data == datetime.now().date():
            css_classes.append('today')
        if day_data.month != month_day:
            css_classes.append('btn-outline-secondary')
            disabled = 'disabled'
        if day_data < datetime.now().date():
            disabled = 'disabled'
        res = '<button type="button" class="{0}" {1} value="{2}">{3}</button>{4}'.format(' '.join(css_classes),
                                                                                         disabled, day_data,
                                                                                         day_data.day, append_br, )
        return res

    c = calendar.Calendar(calendar.MONDAY)
    result_html = '<button disabled class="btn date_picker_item date_picker_day"><b>Пн</b></button>' \
                  '<button disabled class="btn date_picker_item date_picker_day"><b>Вт</b></button>' \
                  '<button disabled class="btn date_picker_item date_picker_day"><b>Ср</b></button>' \
                  '<button disabled class="btn date_picker_item date_picker_day"><b>Чт</b></button>' \
                  '<button disabled class="btn date_picker_item date_picker_day"><b>Пт</b></button>' \
                  '<button disabled class="btn date_picker_item date_picker_day"><b>Сб</b></button>' \
                  '<button disabled class="btn date_picker_item date_picker_day"><b>Вс</b></button><br>'
    for day in c.itermonthdates(year, month):
        date_html = get_date_html(day, month)

        result_html += date_html

    return result_html

amia/appointment/templates/appointment/appointment_input_form.html
<form action="{% url 'appointment:add_appointment' %}" method="post" class="needs-validation" novalidate>{% csrf_token %}
    <div class="g-3">
        <div class="col-12" style="width: calc(60vmin + 40px); margin: 0 auto;">
            <input type="text" class="form-control" style="height: 5px; opacity: 0;" id="id_time_interval" name="time_interval" required>
            <div class="invalid-feedback" >
                Выберите дату и время записи
            </div>
        </div>
        <div class="col-12" style="width: calc(60vmin + 40px); margin: 0 auto;">
            <label class="form-label">Ф.И.О</label>
            <input type="text" class="form-control can_be_disabled" name="last_name" value="{{ last_name }}" required>
            <div class="invalid-feedback">
                Поле является обязательным
            </div>
        </div>
        <div class="col-12" style="width: calc(60vmin + 40px); margin: 0 auto">
            <label class="form-label">Дата рождения</label>
            <input type="text" class="form-control can_be_disabled" name="date_of_birth" value="{{ date_of_birth }}" required>
            <div class="invalid-feedback">
                Поле является обязательным
            </div>
        </div>

        <div class="col-12" style="width: calc(60vmin + 40px); margin: 0 auto;">
            <label class="form-label">Комментарий к записи</label>
            <textarea class="form-control can_be_disabled" name="comment" rows="3">{{ comment }}</textarea>
        </div>
        <input type="hidden" id="id_month" name="month" value="{{ month }}">
        <div class="col-12" align="center">
            <button type="submit" class="btn-my btn-primary-my can_be_disabled">Зарегистрироваться</button>
        </div>
    </div>
</form>

amia/appointment/templates/appointment/date_picker.html
{#<h3>{{ month_selected.month }}</h3>#}

    {{ dates|safe }}

amia/appointment/templates/appointment/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Электронная очередь на ЦТ</title>
{% endblock %}
{% block own_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'appointment/css/main.css' %}">
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        {% include 'dashboard/nav.html' %}
    {% endif %}
    <!--[if !IE]> -->
    {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
    {% endif %}
    <div class="main-center">

        <div class="alert-my alert-primary-my" role="alert">
            <img src="{% static 'appointment/img/favicon.ico' %}"  class="logo-img" alt="" loading="lazy"></a>
            ЭЛЕКТРОННАЯ ОЧЕРЕДЬ НА ЦТ
        </div>
		
		<div>
			<div class="d-flex justify-content-center" style="width:60vmin; margin: 0 auto;">
				{% if month_prev < 1 %}
					<a href="/?month={{ month_prev }}" class="nav-link-my disabled">
				{% else %}

					<a href="/?month={{ month_prev }}" class="nav-link-my">
	 
				{% endif %}
				
			   <div class="nav-month-prev"><i class="fas fa-chevron-left"></i></div>
				</a>
				<div style="margin: 0 auto;"><span class="month-name">{{ month_selected.month }} 2021</span></div>
				{% if month_next > 12 %}
					<a href="/?month={{ month_next }}" class="nav-link-my disabled">
				{% else %}
				
					<a href="/?month={{ month_next }}" class="nav-link-my">
				{% endif %}
				<div class="nav-month-next"><i class="fas fa-chevron-right"></i></div>
				</a>
			</div>
				<div align="center" style="margin-top: 1.5em;">
					<div style="width: 100vmin;">{% include 'appointment/date_picker.html' %}</div>
				</div>
		</div>	
			

        <div id="div_for_intervals"></div><br>

        <div>
            {% include 'appointment/appointment_input_form.html' %}
        </div>
    </div>
    <!-- <![endif]--><!--[if IE]>Ваш браузер не поддерживается<![endif]-->
{% endblock %}

{% block own_js %}
    <script src="{% static 'appointment/js/main.js' %}"></script>
    <script src="{% static 'appointment/js/form_validation.js' %}"></script>
{% endblock %}

amia/appointment/templates/appointment/index2.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'appointment/css/index2.css' %}">

    <title>Index</title>
</head>
<body style="background-color: #eeede9;font-size: 1rem;">
<div class="container">
    <br>
    <br>

    <div class="row" style="-radius: 20px;">
        <div class="col-md-5  rounded-start" style="background-color: #f38989;color: white;">
            <div class="d-flex justify-content-center flex-column" style="height: 100%">
                <div class="text-center" style="font-size: 2rem;">FRIDAY</div>
                <div class="text-center" style="font-size: 2rem;">SEPTEMBER</div>
                <div style="margin-right: auto; margin-left: auto;font-size: 7rem;">12</div>
            </div>
        </div>
        <div class="col-md-7 rounded-end d-flex flex-column justify-content-center" style="background-color: white;">
            <div class="m-3 text-end fw-light" style="font-size: 1.2rem">2021</div>
            <br><br>

            <div class="main-div">
                <select class="form-select form-select-sm mb-3">
                    <option value="1">Январь</option>
                    <option value="2">Февраль</option>
                    <option value="3">Апрель</option>
                    <option value="3">Май</option>
                    <option value="3">Июнь</option>
                    <option value="3">Июль</option>
                    <option value="3">Август</option>
                </select>

                <div class="d-flex flex-row justify-content-between mb-2">
                    <div class="text-center" style="width: 25px;">Пн</div>
                    <div class="text-center" style="width: 25px;">Вт</div>
                    <div class="text-center" style="width: 25px;">Ср</div>
                    <div class=" text-center" style="width: 25px;">Чт</div>
                    <div class=" text-center" style="width: 25px;">Пт</div>
                    <div class=" text-center" style="width: 25px;">Сб</div>
                    <div class=" text-center" style="width: 25px;">Вс</div>
                </div>
                <div class="d-flex flex-row justify-content-between  mb-2">
                    <div class=" text-center fw-bold" style="width: 25px;">1</div>
                    <div class=" text-center fw-bold" style="width: 25px;">2</div>
                    <div class=" text-center fw-bold" style="width: 25px;">3</div>
                    <div class=" text-center fw-bold" style="width: 25px;">4</div>
                    <div class=" text-center fw-bold" style="width: 25px;">5</div>
                    <div class=" text-center fw-bold" style="width: 25px;">6</div>
                    <div class=" text-center fw-bold" style="width: 25px;">7</div>
                </div>
                <div class="d-flex flex-row justify-content-between mb-2">
                    <div class=" text-center" style="width: 25px;">8</div>
                    <div class=" text-center" style="width: 25px;">9</div>
                    <div class=" text-center" style="width: 25px;">10</div>
                    <div class=" text-center" style="width: 25px;">11</div>
                    <div class=" text-center" style="width: 25px;">12</div>
                    <div class=" text-center" style="width: 25px;">13</div>
                    <div class=" text-center" style="width: 25px;">14</div>
                </div>
                <div class="d-flex flex-row justify-content-between  mb-2">
                    <div class=" text-center" style="width: 25px;">15</div>
                    <div class=" text-center" style="width: 25px;">16</div>
                    <div class=" text-center" style="width: 25px;">17</div>
                    <div class=" text-center" style="width: 25px;">18</div>
                    <div class=" text-center" style="width: 25px;">19</div>
                    <div class=" text-center" style="width: 25px;">20</div>
                    <div class=" text-center" style="width: 25px;">21</div>
                </div>
                <div class="d-flex flex-row justify-content-between  mb-2">
                    <div class=" text-center" style="width: 25px;">22</div>
                    <div class=" text-center" style="width: 25px;">23</div>
                    <div class=" text-center" style="width: 25px;">24</div>
                    <div class=" text-center" style="width: 25px;">25</div>
                    <div class=" text-center" style="width: 25px;">26</div>
                    <div class=" text-center" style="width: 25px;">27</div>
                    <div class=" text-center" style="width: 25px;">28</div>
                </div>
                <div class="d-flex flex-row justify-content-between  mb-2">
                    <div class=" text-center" style="width: 25px;">29</div>
                    <div class=" text-center" style="width: 25px;">30</div>
                    <div class=" text-center" style="width: 25px;">31</div>
                    <div class=" text-center" style="width: 25px;"></div>
                    <div class=" text-center" style="width: 25px;"></div>
                    <div class=" text-center" style="width: 25px;"></div>
                    <div class=" text-center" style="width: 25px;"></div>
                </div>
            </div>
            <div class="mt-3"></div>
        </div>
        <div class="mt-3"></div>

        <div>
            <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="exampleInputEmail1"
                                   aria-describedby="emailHelp">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword1">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword1">
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>


            </form>
        </div>
    </div>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
</body>
</html>

amia/appointment/templates/appointment/month_select.html
<select class="form-select can_be_disabled" style="width: 45vmin; margin: 1em 5vmin;" id="id_month_select">
    {% for month_item in months %}
        {% if month_item.month_number == month_selected.month_number %}
            <option value="{{ month_item.month_number }}" selected>{{ month_item.month }}</option>
        {% else %}
            <option value="{{ month_item.month_number }}">{{ month_item.month }}</option>
        {% endif %}
    {% endfor %}
</select>

amia/appointment/templates/appointment/success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Подтверждение записи</title>
{% endblock %}
{% block own_css %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
{% endblock %}

{% block content %}

    <!--[if !IE]> -->

    <div class="container py-4">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold">Уважаемый абитуриент!!!</h1>
                <p class="col-md-12 fs-4" style="text-indent: 1.5em; text-align: justify;">Для подтверждения регистрации и получения пропуска(-ов) на прохождение централизованного тестирования приглашаем Вас после оплаты регистрационного взноса ЛИЧНО явиться {{ date_appointment }} к {{ time }} в пункт регистрации на централизованное тестирование учреждения образования «Академия Министерства внутренних
                    дел Республики Беларусь», расположенный по адресу: г. Минск, пр-т Машерова, 6, ауд. 101А (вход с транспортного КПП).</p>
                 <p class="col-md-12 fs-4" style="text-indent: 1.5em; text-align: justify;">При себе необходимо иметь:</p>
                 <p class="col-md-12 fs-4" style="text-indent: 1.5em; text-align: justify;">- документ, удостоверяющий личность;</p>
                 <p class="col-md-12 fs-4" style="text-indent: 1.5em; text-align: justify;">- документы, подтверждающие право на льготу (при наличии) и их копии.</p>
            </div>
        </div>
    </div>

    <!-- <![endif]--><!--[if IE]>Ваш браузер не поддерживается<![endif]-->
{% endblock %}

{% block own_js %}{% endblock %}