amia/amia/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest import views

router = routers.DefaultRouter()
router.register(r'appointments', views.AppointmentViewSet, basename='Appointment')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointment.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rest/', include(router.urls)),
    path('accounts/', include('django.contrib.auth.urls'))
]

amia/appointment/urls.py
from django.urls import path
from . import views


app_name = 'appointment'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_appointment/', views.add_appointment, name='add_appointment'),
    path('<appointment_id>/success/', views.success, name='success'),
]

amia/dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'dashboard'

urlpatterns = [
    path('', login_required(views.dashboard_main), name='main'),
    path('queue_create/', login_required(views.dashboard_queue_create), name='queue_create'),
]

amia/dashboard/models.py
from django.db import models

# Create your models here.

amia/dashboard/forms.py
from django.forms import ModelForm
from appointment.models import Appointment


class AppointmentForm(ModelForm):

    class Meta:
        model = Appointment
        fields = ['last_name', 'comment', 'is_booked', 'email']

amia/dashboard/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from appointment.models import Appointment
from datetime import datetime, time, timedelta

from dashboard.filters import AppointmentFilter


def dashboard_main(request):
    f = AppointmentFilter(request.GET, queryset=Appointment.objects.all().order_by('date_appointment',
                                                                                   'time_appointment'))
    paginator = Paginator(f.qs, 100)
    page = request.GET.get('page')
    items = paginator.get_page(page)
    return render(request, 'dashboard/dashboard_main.html', {'appointment_list': items,
                                                             'filter': f,
                                                             })


def dashboard_queue_create(request):
    if request.method == 'POST':
        if validate_data():

            Appointment.objects.all().delete()
            date_from = datetime.strptime(request.POST['date_from'], '%Y-%m-%d')
            date_till = datetime.strptime(request.POST['date_till'], '%Y-%m-%d')
            work_day_from = int(request.POST['work_day_from'])
            work_day_till = int(request.POST['work_day_till'])
            time_interval = int(request.POST['time_interval'])

            time_intervals = get_time_intervals(work_day_from, work_day_till, time_interval)
            dates_for_appointments = get_dates(date_from, date_till)

            for date_f_a in dates_for_appointments:
                for time_inter in time_intervals:
                    appointment = Appointment(
                        date_appointment=date_f_a,
                        time_appointment=time_inter
                    )
                    appointment.save()
            return HttpResponseRedirect(reverse('dashboard:main'))
    else:
        return render(request, 'dashboard/queue_input_form.html')


def validate_data(data=None):
    return True


def get_minute_intervals(time_interval):
    def time_range(start, end, delta):
        current = start
        while current < end:
            yield current
            current += delta

    dts = [dt for dt in time_range(0, 60, time_interval)]
    return dts


def get_time_intervals(work_day_from, work_day_till, time_interval):
    minutes_intervals = get_minute_intervals(time_interval)
    time_intervals = []
    for hour in range(work_day_from, work_day_till):
        for minutes in minutes_intervals:
            t = time(hour, minutes)
            time_intervals.append(t)
    return time_intervals


def get_dates(date_from, date_till):
    def date_range(start, end, delta):
        current = start
        while current <= end:
            yield current
            current += delta

    dates = [d for d in date_range(date_from, date_till, timedelta(days=1))]
    return dates

amia/dashboard/templates/dashboard/dashboard_main.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load url_replace %}
{% block title %}
    <title>Панель управления</title>
{% endblock %}
{% block own_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/main.css' %}">
{% endblock %}

{% block content %}
    {% include 'dashboard/nav.html' %}

    <div class="container">
        <br>
        <br>
        <div class="card" style="width: 100%;">
            <div class="card-body">
                <h5 class="card-title">Ваша элетронная очередь</h5>
                <p class="card-text">В таблице размещен список элетронной очереди. При необходимости поиска используйте
                    форму</p>
                {% if appointment_list %}
                    <a href="{% url 'dashboard:queue_create' %}" class="btn btn-danger">
                        Пересоздать очередь (с удалением всех записей!!!)</a>
                {% else %}
                    <a href="{% url 'dashboard:queue_create' %}" class="btn btn-primary">
                        Создать новую очередь
                    </a>
                {% endif %}
                </a>
            </div>
        </div>
        <br>


        <form action="{% url 'dashboard:main' %}" method="get">
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Фамилия</label>
                        {% render_field filter.form.last_name class+="form-control" %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Дата записи</label>
                        {% render_field filter.form.date_appointment class+="form-control" %}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Забронировано</label>
                        {% render_field filter.form.is_booked class+="form-control" %}
                        {#                        {% render_field filter['o'].field.last_name class+="form-control" %}#}
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Поиск</button>
            <a href="{% url 'dashboard:main' %}" class="btn btn-success">Сбросить фильтр</a>
        </form>
    </div>
    <br>
    {% if appointment_list %}
        <div class="container">
            <h3 class="mt-2 mb-3">Найдено записей - {{ filter.qs.count }}</h3>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">
                        <a href="?{% url_replace request 'ordering' 'last_name' %}"><i class="fas fa-sort-amount-up-alt"></i></a>
                        <a href="?{% url_replace request 'ordering' '-last_name' %}"><i class="fas fa-sort-amount-up"></i></a>
                        Фамилия Имя Отчество</th>
                    <th scope="col">
{#                        <a href="?{% url_replace request 'ordering' 'date_of_birth' %}"><i class="fas fa-sort-amount-up-alt"></i></a>#}
{#                        <a href="?{% url_replace request 'ordering' '-date_of_birth' %}"><i class="fas fa-sort-amount-up"></i></a>#}
                        Дата рождения</th>
                    <th scope="col">Дата и время записи</th>
                    <th scope="col">Забронировано <input class="form-check-input is_booked_all_checkbox" type="checkbox"
                                                         value="" id="is_booked_all_checkbox_id"></th>
                    <th scope="col">Комментарий к записи</th>
                </tr>
                </thead>
                <tbody>
                {% for item in appointment_list %}
                    <tr>
                        <th scope="row">
                            <input type="text" class="form-control no_border_input" id="id_last_name_{{ item.id }}" value="{{ item.last_name|default_if_none:"Нет данных" }}">
                        </th>
                        <td>
                            <input type="date" class="form-control no_border_input" id="id_date_of_birth_{{ item.id }}" value="{{ item.date_of_birth }}">
                        </td>
                        {#                        <td>{{ item.email|default_if_none:"Нет данных" }}</td>#}
                        <td>{{ item.date_appointment }} {{ item.time_appointment }}</td>
                        <td>
                            {% if item.is_booked %}
                                <input class="form-check-input is_booked_checkbox may_be_disabled" type="checkbox"
                                       value="{{ item.id }}" checked>
                                <nobr>{{ item.date_of_write }}</nobr>
                            {% else %}
                                <input class="form-check-input is_booked_checkbox may_be_disabled" type="checkbox"
                                       value="{{ item.id }}">
                            {% endif %}
                        </td>
                        <td>
                            <input type="text" class="form-control no_border_input" id="id_comment_{{ item.id }}" value="{{ item.comment|default_if_none:"Нет данных" }}">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <button type="button" class="btn btn-primary mb-4 may_be_disabled" id="save_button">Сохранить</button>
            {% csrf_token %}

        </div>

    {% else %}
        <p style="margin-left: 12px;">Список пуст!</p>
    {% endif %}

{% endblock %}

{% block own_js %}
    <script src="{% static 'dashboard/js/dashboard_main.js' %}"></script>
{% endblock %}

amia/dashboard/templates/dashboard/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'appointment:index' %}"><img src="{% static 'appointment/img/favicon.ico' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">&nbsp;Академия МВД</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
{#            {% if user.is_authenticated %}#}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'appointment:index' %}">Страница записи на ЦТ</a>
                    </li>
                    <li class="nav-item">
                    <li><a class="nav-link" href="{% url 'dashboard:main' %}">Работа с записями</a></li>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выход из системы</a>
                    </li>
                </ul>
{#            {% endif %}#}
        </div>
    </div>
</nav>

amia/dashboard/templates/dashboard/queue_input_form.html
{% extends 'base.html' %}

{% block title %}
    <title>Создание новой очереди</title>
{% endblock %}
{% block own_css %}
{% endblock %}

{% block content %}
    {% include 'dashboard/nav.html' %}
    <br>
    <div class="container">
        <form action="{% url 'dashboard:queue_create' %}" method="POST">{% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label class="form-label">Дата начала работы очереди</label>
                        <input type="date" class="form-control" name="date_from" value="{% now "Y-m-d" %}" min="{% now "Y-m-d" %}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label class="form-label">Дата окончания работы очереди</label>
                        <input type="date" class="form-control" name="date_till" value="{% now "Y-m-d" %}" required>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="mb-3">
                        <label class="form-label">Рабочий день с (часов)</label>
                        <select class="form-select" name="work_day_from" required>
                            <option value="8" selected>8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19">19</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="mb-3">
                        <label class="form-label">Рабочий день по (часов)</label>
                        <select class="form-select" name="work_day_till" required>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                            <option value="13">13</option>
                            <option value="14">14</option>
                            <option value="15">15</option>
                            <option value="16">16</option>
                            <option value="17">17</option>
                            <option value="18">18</option>
                            <option value="19" selected>19</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="mb-3">
                        <label class="form-label">Временной интервал (минут)</label>
                        <select class="form-select" name="time_interval" required>
                            <option value="5">5</option>
                            <option value="10">10</option>
                            <option value="15">15</option>
                            <option value="20" selected>20</option>
                            <option value="25">25</option>
                            <option value="30">30</option>
                        </select>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Создать очередь</button>
        </form>

    </div>

{% endblock %}

{% block own_js %}
{% endblock %}